### PR TITLE
Member model

### PR DESCRIPTION
**Pull request by rurounijones**
Moved the member model from ActiveResource to ActiveRecord.

This is quite a large change and I may have stepped on others' toes.

Will require a rake db:migrate 
I have added a rake task meetup:import_members which will need to be added to the heroku scheduler. 

I have updated the existing tests for the member model but have not written tests for the importer yet because I am a bit leary of VCR (Or at least how we appear to be using it, will discuss this on mailing list or a github issue).

I am putting this pull request up now in case you want to pull before those tests are written in the interest of speed.

### CODE REVIEW

**Comment by rurounijones** [comment]
I also made the record saving use save! instead of save so that an exception would be raised on a failure. This would then hopefully be picked up by an exception addon like airbrake (If we choose to get it)

**Comment by rurounijones** [comment]
For your github username to be imported go to the tokyorails group on meetup.com (or tokyorails.org) and then navigate to "Members" -> "My profile"

Edit your profile and add "github:username" to the "Additional Information" field in the "Extras" field

**Comment by tapster** [comment]
thanks for this. should help us get moving

**Comment by tapster** [comment]
got it working locally after some issues with SSL certs in ruby 1.9.3. Turned out to be know issues and resolved by going back to 1.9.2

however, 1.9.2 has some issue with yard ! https://github.com/lsegal/yard/issues/382 which is exactly what I get

what ruby are you running locally with? I'll get back to it tomorrow to try and resolve. 

cheers

**Comment by rurounijones** [comment]
Strange, I am running the Ruby 1.9.3-p0 specified in the project .rvmc file. However I am running on Ubuntu Linux 11.10, not OSX.

Is the SSL problem specific to OSX?

**Comment by tapster** [comment]
looks that way yes. Im seeing the same issue as here https://github.com/arsduo/koala/issues/146 . after setting up the CA Cert I get the segfault

digging into that they posted a ruby bug http://redmine.ruby-lang.org/issues/5655 that links to a possible solution. 

will try and have a look tomorrow at some point

btw, I got your commit working by removing yard temprarily - works well

**Comment by rurounijones** [comment]
For the moment we don't absolutely need yard installed so I am happy if you want to go ahead without it for the moment.

If you do want to pull into the master repo the I will fork off of that again and then write the import script tests using simple webmock mocks instead of VCR as an example like I mentioned in #13.

If you do not want to pull without those tests then I will make a new branch based off of this one demonstrating how I would test it using webmock.

**Pull request merged**
